# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
baseURL = "https://splashof.ink/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20


buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[permalinks]
  blogs = "/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
