languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Splash of Ink"
# logo = "img/logo.png"
description = "Blogs & Stories"
copyright = "© Sean Johnson"


[author]
  name = "a collection of blogs and fiction"
  image = "img/avatar-small.jpg"
  headline = "by sean johnson"
  links = [
    { mastodon = "https://skj.social/@sean"},
    { github   = "https://github.com/ttyS0"},
    { lastfm   = "https://www.last.fm/user/skj_dev"},
    { trakt    = "https://trakt.tv/users/skj-tv/history"}
  ]

